In [1]:
from hdx_client import HdxClient
import pandas as pd

In [19]:
from processing.food_prices_processing import get_clean_data

In [20]:
df = get_clean_data()

Downloaded file to: ..\data\hdx\Sudan - Food Prices8.csv
Successfully loaded 'Sudan - Food Prices' into variable dataframe
Downloaded file to: ..\data\hdx\South Sudan - Food Prices3.csv
Successfully loaded 'South Sudan - Food Prices' into variable dataframe

In [21]:
df

          admin1 year_month  price_millet  price_sorghum  price_wheat_flour
0          Abyei    2017-07           NaN            NaN               1.55
1          Abyei    2017-08           NaN            NaN               1.55
2          Abyei    2017-09           NaN            NaN               1.55
3          Abyei    2017-10           NaN            NaN               1.55
4          Abyei    2017-11           NaN            NaN               1.55
...          ...        ...           ...            ...                ...
1705  White Nile    2024-08      3.460000       2.750000               5.85
1706  White Nile    2024-09      4.771429       2.783333               6.68
1707  White Nile    2024-10      3.131429       2.680000               5.84
1708  White Nile    2024-11      3.400000       2.226667               3.01
1709  White Nile    2024-12      3.697143       2.643333               3.01

[1710 rows x 5 columns]

## GDF

In [ ]:
data_name = 'cod-ab-sdn'

In [ ]:
hdx = HdxClient()
gdf = hdx.get_data(dataset_name=data_name, file_name="admin1", file_type='geojson')

In [ ]:
acled = pd.read_csv("../data/all_data.csv")

In [ ]:
country_name_mapping = {
    'Abyei PCA': 'Abyei',
    'Aj Jazirah': 'Al Jazirah'
}

gdf["adm1_name"] = gdf["adm1_name"].replace(country_name_mapping)

In [ ]:
gdf.columns

In [ ]:
# hdx = HdxClient()
# df_sudan = hdx.get_data(dataset_name="wfp-food-prices-for-sudan", file_name="Sudan - Food Prices", file_type='csv')
# df_south_sudan = hdx.get_data(dataset_name="wfp-food-prices-for-south-sudan", file_name="South Sudan - Food Prices", file_type='csv')
#
# # https://www.britannica.com/place/Sudan/Agriculture-forestry-and-fishing
# primary_commodities = ["Sorghum", "Millet", "Wheat flour"]
#
# df_filtered = df[
#     (df["commodity"].isin(primary_commodities))
#     & (df["pricetype"] == "Retail")
#     & (df["priceflag"] == "actual")
# ].copy()
#
# model_df = df_filtered[
#     ["date", "admin1", "admin2", "commodity", "unit", "usdprice"]
# ]
#
# def clean_state_names(value):
#     key = str(value).strip()
#     return SUDAN_STATE_MAPPING.get(key, value)  # Returns original if not matched
#
#
# renamed_df = model_df.copy()
# renamed_df["admin1"] = model_df["admin1"].apply(clean_state_names)
#
# # Now both are DataFrames!
# find_unmatched_unique_values(acled, renamed_df, "admin1")

In [ ]:
# hdx = HdxClient()
# df_sudan = hdx.get_data(dataset_name="wfp-food-prices-for-sudan", file_name="Sudan - Food Prices", file_type='csv')
# df_south_sudan = hdx.get_data(dataset_name="wfp-food-prices-for-south-sudan", file_name="South Sudan - Food Prices",
#                               file_type='csv')

In [ ]:
# df_south_sudan_abyei = df_south_sudan[
#     df_south_sudan["admin1"] == "Abyei"]
#
# df_combined = pd.concat([df_sudan, df_south_sudan_abyei], ignore_index=True)
#
# # https://www.britannica.com/place/Sudan/Agriculture-forestry-and-fishing
# primary_commodities = ["Sorghum", "Millet", "Wheat flour"]
#
# df_filtered = df_combined[
#     (df_combined["commodity"].isin(primary_commodities))
#     & (df_combined["pricetype"] == "Retail")
#     & (df_combined["priceflag"] == "actual")
# ].copy()
#
# model_df = df_filtered[
#     ["date", "admin1", "admin2", "commodity", "unit", "usdprice"]
# ].copy()
#
# def clean_state_names(value):
#     if pd.isna(value):
#         return value
#     key = str(value).strip()
#     return SUDAN_STATE_MAPPING.get(key, value)
#
# renamed_df = model_df.copy()
# renamed_df["admin1"] = renamed_df["admin1"].apply(clean_state_names)

In [ ]:
# def find_unmatched_unique_values(df1, df2, column_name):
#     """Finds unique values in a specified column that exist in one dataframe
#
#     but not the other.
#     """
#     if column_name not in df1.columns or column_name not in df2.columns:
#         raise KeyError(f"Column '{column_name}' must exist in both DataFrames.")
#
#     set1 = set(df1[column_name].dropna().unique())
#     set2 = set(df2[column_name].dropna().unique())
#
#     only_in_df1 = set1 - set2
#     only_in_df2 = set2 - set1
#     all_unmatched = set1 ^ set2
#
#     return {
#         "only_in_df1": sorted(list(only_in_df1)),
#         "only_in_df2": sorted(list(only_in_df2)),
#         "all_unmatched": sorted(list(all_unmatched)),
#     }

In [ ]:
# acled = pd.read_csv("../data/all_data.csv")
# find_unmatched_unique_values(acled, model_df, "admin1")

In [2]:
SUDAN_STATE_MAPPING = {"Al Gezira": "Al Jazirah",
     "Nile": "River Nile",
     "Eastern Darfur": "East Darfur",
    'Abyei PCA': 'Abyei',
    'Aj Jazirah': 'Al Jazirah'}

In [13]:
def read_food_prices():
    hdx = HdxClient()
    df_sudan = hdx.get_data(dataset_name="wfp-food-prices-for-sudan", file_name="Sudan - Food Prices", file_type='csv')
    df_south_sudan = hdx.get_data(dataset_name="wfp-food-prices-for-south-sudan", file_name="South Sudan - Food Prices",
                file_type='csv')

    df_abyei = df_south_sudan[df_south_sudan["market"] == "Abyei"].copy()
    df_abyei["admin1"] = "Abyei"

    df_combined = pd.concat([df_sudan, df_abyei], ignore_index=True)

    primary_commodities = ["Sorghum", "Millet", "Wheat flour"]

    df_filtered = df_combined[
        (df_combined["commodity"].isin(primary_commodities))
        & (df_combined["pricetype"] == "Retail")
        & (df_combined["priceflag"].isin(["actual", "aggregate"]))
    ].copy()

    df_filtered_cols = df_filtered[
        ["date", "admin1", "admin2", "market", "commodity", "unit", "usdprice"]
    ].copy()

    def clean_state_names(value):
        return SUDAN_STATE_MAPPING.get(value, value)


    renamed_df = df_filtered_cols.copy()
    renamed_df["admin1"] = df_filtered_cols["admin1"].apply(clean_state_names)
    renamed_df["date"] = pd.to_datetime(renamed_df["date"])
    renamed_df['year_month'] = renamed_df['date'].dt.to_period('M')
    renamed_df["unit_weight_in_kg"] = (
            renamed_df['unit']
            .str.extract(r'([\d.]+)', expand=False)
            .astype(float)
            .fillna(1.0)
        )
    renamed_df["usdprice"] = pd.to_numeric(renamed_df["usdprice"], errors="coerce")
    renamed_df['usdprice_per_kg'] = renamed_df['usdprice'] / renamed_df['unit_weight_in_kg']
    return renamed_df

In [14]:
food_prices_df = read_food_prices()

Downloaded file to: ..\data\hdx\Sudan - Food Prices7.csv
Successfully loaded 'Sudan - Food Prices' into variable dataframe
Downloaded file to: ..\data\hdx\South Sudan - Food Prices2.csv
Successfully loaded 'South Sudan - Food Prices' into variable dataframe

In [15]:
food_prices_df

,date,admin1,admin2,market,commodity,unit,usdprice,year_month,unit_weight_in_kg,usdprice_per_kg
190,2003-01-15,East Darfur,Ed Daein,Eddein,Millet,3.5 KG,0.66,2003-01,3.5,0.188571
193,2003-01-15,Kassala,Kassala,Kassala,Millet,3.5 KG,0.40,2003-01,3.5,0.114286
194,2003-01-15,Kassala,Kassala,Kassala,Sorghum,3 KG,0.47,2003-01,3.0,0.156667
198,2003-01-15,North Darfur,El Fasher,Al Fashir,Millet,3.5 KG,0.77,2003-01,3.5,0.220000
199,2003-01-15,North Darfur,El Fasher,Al Fashir,Sorghum,3 KG,0.68,2003-01,3.0,0.226667
...,...,...,...,...,...,...,...,...,...,...
22130,2026-01-15,Abyei,Twic,Abyei,Wheat flour,KG,2.01,2026-01,1.0,2.010000
22147,2026-02-15,Abyei,Twic,Abyei,Wheat flour,KG,1.78,2026-02,1.0,1.780000
22166,2026-03-15,Abyei,Twic,Abyei,Wheat flour,KG,1.78,2026-03,1.0,1.780000
22186,2026-06-15,Abyei,Twic,Abyei,Wheat flour,KG,2.16,2026-06,1.0,2.160000
22206,2026-07-15,Abyei,Twic,Abyei,Wheat flour,KG,2.10,2026-07,1.0,2.100000

In [16]:
def process_and_pivot_food_prices(df_prices: pd.DataFrame) -> pd.DataFrame:
    df = df_prices.copy()

    df_grouped = (
        df.groupby(["admin1", "year_month", "commodity"])["usdprice_per_kg"]
        .median()
        .reset_index()
    )

    all_regions = df_grouped["admin1"].unique()
    all_months = pd.period_range(
        df_grouped["year_month"].min(), df_grouped["year_month"].max(), freq="M"
    )
    all_commodities = df_grouped["commodity"].unique()

    full_index = pd.MultiIndex.from_product(
        [all_regions, all_months, all_commodities],
        names=["admin1", "year_month", "commodity"],
    )

    df_expanded = (
        df_grouped.set_index(["admin1", "year_month", "commodity"])
        .reindex(full_index)
        .reset_index()
        .sort_values(["admin1", "commodity", "year_month"])
    )

    df_expanded["usdprice_per_kg"] = df_expanded.groupby(
        ["admin1", "commodity"]
    )["usdprice_per_kg"].transform(lambda x: x.ffill().bfill())

    df_pivoted = df_expanded.pivot(
        index=["admin1", "year_month"],
        columns="commodity",
        values="usdprice_per_kg",
    ).reset_index()

    df_pivoted.columns.name = None
    df_pivoted = df_pivoted.rename(
        columns={
            "Millet": "price_millet",
            "Sorghum": "price_sorghum",
            "Wheat flour": "price_wheat_flour",
        }
    )

    return df_pivoted

In [17]:
pivoted = process_and_pivot_food_prices(food_prices_df)

In [18]:
pivoted

          admin1 year_month  price_millet  price_sorghum  price_wheat_flour
0          Abyei    2003-01           NaN            NaN               1.55
1          Abyei    2003-02           NaN            NaN               1.55
2          Abyei    2003-03           NaN            NaN               1.55
3          Abyei    2003-04           NaN            NaN               1.55
4          Abyei    2003-05           NaN            NaN               1.55
...          ...        ...           ...            ...                ...
5372  White Nile    2026-03      3.211429       2.066667               4.17
5373  White Nile    2026-04      3.331429       2.500000               5.71
5374  White Nile    2026-05      3.748571       2.620000               5.56
5375  White Nile    2026-06      3.882857       2.290000               5.55
5376  White Nile    2026-07      3.882857       2.290000               5.55

[5377 rows x 5 columns]

In [ ]:
# df_abyei = df_south_sudan[df_south_sudan["market"] == "Abyei"].copy()
# df_abyei["admin1"] = "Abyei"
#
# df_combined = pd.concat([df_sudan, df_abyei], ignore_index=True)
#
# primary_commodities = ["Sorghum", "Millet", "Wheat flour"]
#
# df_filtered = df_combined[
#     (df_combined["commodity"].isin(primary_commodities))
#     & (df_combined["pricetype"] == "Retail")
#     & (df_combined["priceflag"].isin(["actual", "aggregate"]))
# ].copy()
#
# model_df = df_filtered[
#     ["date", "admin1", "admin2", "market", "commodity", "unit", "usdprice"]
# ].copy()
#
# SUDAN_STATE_MAPPING = {"Al Gezira": "Al Jazirah",
#  "Nile": "River Nile",
#  "Eastern Darfur": "East Darfur"}
#
#
# def clean_state_names(value):
#     return SUDAN_STATE_MAPPING.get(value, value)
#
#
# renamed_df = model_df.copy()
# renamed_df["admin1"] = renamed_df["admin1"].apply(clean_state_names)
#
# unmatched = find_unmatched_unique_values(acled, renamed_df, "admin1")
#
# print("States only in ACLED:", unmatched["only_in_df1"])
# print("States only in WFP Food Prices:", unmatched["only_in_df2"])

In [ ]:
renamed_df["date"] = pd.to_datetime(renamed_df["date"])
renamed_df['year_month'] = renamed_df['date'].dt.to_period('M')

In [ ]:
renamed_df