In [2]:
from hdx_client import HdxClient
import pandas as pd

## GDF

In [3]:
data_name = 'cod-ab-sdn'

In [4]:
hdx = HdxClient()
gdf = hdx.get_data(dataset_name=data_name, file_name="admin1", file_type='geojson')

2026-07-30 12:53:12.066 | INFO     | hdx.api.configuration:__init__:89 - No HDX base configuration parameter. Using default base configuration file: C:\Users\evely\PycharmProjects\msc-final-project\.venv\Lib\site-packages\hdx\api\hdx_base_configuration.yaml.
2026-07-30 12:53:12.067 | INFO     | hdx.api.configuration:__init__:92 - Loading HDX base configuration from: C:\Users\evely\PycharmProjects\msc-final-project\.venv\Lib\site-packages\hdx\api\hdx_base_configuration.yaml
2026-07-30 12:53:12.103 | INFO     | hdx.api.configuration:__init__:123 - No HDX configuration parameter and no configuration file at default path: C:\Users\evely\.hdx_configuration.yaml.
2026-07-30 12:53:12.104 | INFO     | hdx.api.configuration:__init__:203 - Read only access to HDX: True

Downloaded file to: ..\data\hdx\sdn_admin_boundaries.geojson.zip4.geojson
Extracting zip archive...
Successfully loaded 'admin1' into variable 'gdf'!

In [5]:
acled = pd.read_csv("../data/all_data.csv")

In [6]:
country_name_mapping = {
    'Abyei PCA': 'Abyei',
    'Aj Jazirah': 'Al Jazirah'
}

gdf["adm1_name"] = gdf["adm1_name"].replace(country_name_mapping)

In [7]:
gdf.columns

Index(['adm1_name', 'adm1_name1', 'adm1_name2', 'adm1_name3', 'adm1_pcode',
       'adm0_name', 'adm0_name1', 'adm0_name2', 'adm0_name3', 'adm0_pcode',
       'valid_on', 'valid_to', 'area_sqkm', 'version', 'lang', 'lang1',
       'lang2', 'lang3', 'adm1_ref_name', 'center_lat', 'center_lon',
       'geometry'],
      dtype='object')

In [13]:
hdx = HdxClient()
df_sudan = hdx.get_data(dataset_name="wfp-food-prices-for-sudan", file_name="Sudan - Food Prices", file_type='csv')
df_south_sudan = hdx.get_data(dataset_name="wfp-food-prices-for-south-sudan", file_name="South Sudan - Food Prices", file_type='csv')

# https://www.britannica.com/place/Sudan/Agriculture-forestry-and-fishing
primary_commodities = ["Sorghum", "Millet", "Wheat flour"]

df_filtered = df[
    (df["commodity"].isin(primary_commodities))
    & (df["pricetype"] == "Retail")
    & (df["priceflag"] == "actual")
].copy()

model_df = df_filtered[
    ["date", "admin1", "admin2", "commodity", "unit", "usdprice"]
]

def clean_state_names(value):
    key = str(value).strip()
    return SUDAN_STATE_MAPPING.get(key, value)  # Returns original if not matched


renamed_df = model_df.copy()
renamed_df["admin1"] = model_df["admin1"].apply(clean_state_names)

# Now both are DataFrames!
find_unmatched_unique_values(acled, renamed_df, "admin1")

Downloaded file to: ..\data\hdx\Sudan - Food Prices1.csv
Successfully loaded 'Sudan - Food Prices' into variable 'gdf'!

In [38]:
hdx = HdxClient()
df_sudan = hdx.get_data(dataset_name="wfp-food-prices-for-sudan", file_name="Sudan - Food Prices", file_type='csv')
df_south_sudan = hdx.get_data(dataset_name="wfp-food-prices-for-south-sudan", file_name="South Sudan - Food Prices",
                              file_type='csv')

Downloaded file to: ..\data\hdx\Sudan - Food Prices3.csv
Successfully loaded 'Sudan - Food Prices' into variable 'gdf'!
Downloaded file to: ..\data\hdx\South Sudan - Food Prices.csv
Successfully loaded 'South Sudan - Food Prices' into variable 'gdf'!

In [58]:
df_south_sudan

,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,unit,priceflag,pricetype,currency,price,usdprice
0,2006-01-15,Central Equatoria,Juba,Konyokonyo,1388,4.85,31.6,cereals and tubers,"Sorghum (white, imported)",510,3.5 KG,actual,Retail,SSP,4.5,1.53
1,2006-01-15,Upper Nile,Malakal,Malakal,1389,9.53,31.66,cereals and tubers,Millet (white),146,3.5 KG,actual,Retail,SSP,3.23,1.09
2,2006-01-15,Upper Nile,Malakal,Malakal,1389,9.53,31.66,cereals and tubers,"Sorghum (white, imported)",510,3.5 KG,actual,Retail,SSP,3.2,1.08
3,2006-02-15,Central Equatoria,Juba,Konyokonyo,1388,4.85,31.6,cereals and tubers,"Sorghum (white, imported)",510,3.5 KG,actual,Retail,SSP,4.5,1.53
4,2006-02-15,Upper Nile,Malakal,Malakal,1389,9.53,31.66,cereals and tubers,Millet (white),146,3.5 KG,actual,Retail,SSP,4.38,1.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53726,2026-07-15,Western Equatoria,Yambio,Makpandu,3031,4.74,28.68,vegetables and fruits,Cassava leaves,455,KG,aggregate,Retail,SSP,6000,1.26
53727,2026-07-15,Western Equatoria,Yambio,Makpandu,3031,4.74,28.68,vegetables and fruits,Onions,173,KG,aggregate,Retail,SSP,29000,6.09
53728,2026-07-15,Western Equatoria,Yambio,Makpandu,3031,4.74,28.68,vegetables and fruits,Pumpkin leaves,1223,KG,aggregate,Retail,SSP,6000,1.26
53729,2026-07-15,Western Equatoria,Yambio,Makpandu,3031,4.74,28.68,vegetables and fruits,Sukuma wiki,1250,KG,aggregate,Retail,SSP,9000,1.89
53730,2026-07-15,Western Equatoria,Yambio,Makpandu,3031,4.74,28.68,vegetables and fruits,Tomatoes,114,KG,aggregate,Retail,SSP,16000,3.36

In [55]:
# df_south_sudan_abyei = df_south_sudan[
#     df_south_sudan["admin1"] == "Abyei"]
#
# df_combined = pd.concat([df_sudan, df_south_sudan_abyei], ignore_index=True)
#
# # https://www.britannica.com/place/Sudan/Agriculture-forestry-and-fishing
# primary_commodities = ["Sorghum", "Millet", "Wheat flour"]
#
# df_filtered = df_combined[
#     (df_combined["commodity"].isin(primary_commodities))
#     & (df_combined["pricetype"] == "Retail")
#     & (df_combined["priceflag"] == "actual")
# ].copy()
#
# model_df = df_filtered[
#     ["date", "admin1", "admin2", "commodity", "unit", "usdprice"]
# ].copy()
#
# def clean_state_names(value):
#     if pd.isna(value):
#         return value
#     key = str(value).strip()
#     return SUDAN_STATE_MAPPING.get(key, value)
#
# renamed_df = model_df.copy()
# renamed_df["admin1"] = renamed_df["admin1"].apply(clean_state_names)

In [26]:
def find_unmatched_unique_values(df1, df2, column_name):
    """Finds unique values in a specified column that exist in one dataframe

    but not the other.
    """
    if column_name not in df1.columns or column_name not in df2.columns:
        raise KeyError(f"Column '{column_name}' must exist in both DataFrames.")

    set1 = set(df1[column_name].dropna().unique())
    set2 = set(df2[column_name].dropna().unique())

    only_in_df1 = set1 - set2
    only_in_df2 = set2 - set1
    all_unmatched = set1 ^ set2

    return {
        "only_in_df1": sorted(list(only_in_df1)),
        "only_in_df2": sorted(list(only_in_df2)),
        "all_unmatched": sorted(list(all_unmatched)),
    }

In [27]:
acled = pd.read_csv("../data/all_data.csv")
find_unmatched_unique_values(acled, model_df, "admin1")

{'only_in_df1': ['Abyei', 'Al Jazirah', 'East Darfur', 'River Nile'],
 'only_in_df2': ['Al Gezira', 'Eastern Darfur', 'Nile'],
 'all_unmatched': ['Abyei',
  'Al Gezira',
  'Al Jazirah',
  'East Darfur',
  'Eastern Darfur',
  'Nile',
  'River Nile']}

In [66]:
df_abyei = df_south_sudan[df_south_sudan["market"] == "Abyei"].copy()
df_abyei["admin1"] = "Abyei"

df_combined = pd.concat([df_sudan, df_abyei], ignore_index=True)

primary_commodities = ["Sorghum", "Millet", "Wheat flour"]

df_filtered = df_combined[
    (df_combined["commodity"].isin(primary_commodities))
    & (df_combined["pricetype"] == "Retail")
    & (df_combined["priceflag"].isin(["actual", "aggregate"]))
].copy()

model_df = df_filtered[
    ["date", "admin1", "admin2", "market", "commodity", "unit", "usdprice"]
].copy()

SUDAN_STATE_MAPPING = {"Al Gezira": "Al Jazirah",
 "Nile": "River Nile",
 "Eastern Darfur": "East Darfur"}


def clean_state_names(value):
    return SUDAN_STATE_MAPPING.get(value, value)


renamed_df = model_df.copy()
renamed_df["admin1"] = renamed_df["admin1"].apply(clean_state_names)

unmatched = find_unmatched_unique_values(acled, renamed_df, "admin1")

print("States only in ACLED:", unmatched["only_in_df1"])
print("States only in WFP Food Prices:", unmatched["only_in_df2"])

States only in ACLED: []
States only in WFP Food Prices: []

In [68]:
renamed_df["date"] = pd.to_datetime(renamed_df["date"])
renamed_df['year_month'] = renamed_df['date'].dt.to_period('M')

In [69]:
renamed_df

,date,admin1,admin2,market,commodity,unit,usdprice,year_month
190,2003-01-15,East Darfur,Ed Daein,Eddein,Millet,3.5 KG,0.66,2003-01
193,2003-01-15,Kassala,Kassala,Kassala,Millet,3.5 KG,0.4,2003-01
194,2003-01-15,Kassala,Kassala,Kassala,Sorghum,3 KG,0.47,2003-01
198,2003-01-15,North Darfur,El Fasher,Al Fashir,Millet,3.5 KG,0.77,2003-01
199,2003-01-15,North Darfur,El Fasher,Al Fashir,Sorghum,3 KG,0.68,2003-01
...,...,...,...,...,...,...,...,...
22130,2026-01-15,Abyei,Twic,Abyei,Wheat flour,KG,2.01,2026-01
22147,2026-02-15,Abyei,Twic,Abyei,Wheat flour,KG,1.78,2026-02
22166,2026-03-15,Abyei,Twic,Abyei,Wheat flour,KG,1.78,2026-03
22186,2026-06-15,Abyei,Twic,Abyei,Wheat flour,KG,2.16,2026-06
22206,2026-07-15,Abyei,Twic,Abyei,Wheat flour,KG,2.1,2026-07